name: Terraform Documentation Automation

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main
    

jobs:
  generate-documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Install terraform-docs
      run: |
        sudo apt-get install -y unzip
        curl -sLO https://github.com/terraform-docs/terraform-docs/releases/download/v0.14.1/terraform-docs-v0.14.1-linux-amd64.tar.gz
        tar -xzf terraform-docs-v0.14.1-linux-amd64.tar.gz
        sudo mv terraform-docs /usr/local/bin/

    - name: Generate Terraform documentation
      run: terraform-docs markdown . > README.md

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/terraform-docs:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/terraform-docs:latest

  deploy:
    runs-on: ubuntu-latest
    needs: generate-documentation

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to GCP
      run: |
        gcloud run deploy terraform-docs \
          --image=${{ secrets.DOCKER_USERNAME }}/terraform-docs:latest \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated
